apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaskdemo
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Manisha148/kubernetesmanifest
    path: kubernetesmanifest/deployment.yaml
    targetRevision: HEAD
  project: default
