apiVersion: apps/v1
kind: Deployment
metadata:
  name: SecondInnovation
spec:
  selector:
    matchLabels:
      app: SecondInnovation
  replicas: 3
  template:
    metadata:
      labels:
        app: SecondInnovation
    spec:
      containers:
        - name: SecondInnovation
          image: manishaverma/deployrepo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: SecondInnovation-service
spec:
  selector:
    app: SecondInnovation
  ports:
    - protocol: "TCP"
      port: 9090
      targetPort: 9090
  type: LoadBalancer
