apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test-app
spec:
  selector:
    matchLabels:
      app: flask-test-app
  replicas: 3
  template:
    metadata:
      labels:
        app: flask-test-app
    spec:
      containers:
        - name: flask-test-app
          image: manishaverma/deployrepo
          imagePullPolicy: IfNotPresent
          ports:
	@@ -22,10 +22,10 @@ spec:
apiVersion: v1
kind: Service
metadata:
  name: flask-test-service
spec:
  selector:
    app: flask-test-app
  ports:
    - protocol: "TCP"
      port: 9090
