apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskdemo
  labels:
    app: flaskdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskdemo
  template:
    metadata:
      labels:
        app: flaskdemo
    spec:
      containers:
      - name: flaskdemo
        image: 269001393029.dkr.ecr.us-east-1.amazonaws.com/pythonflask
        ports:
        - containerPort: 8888
      imagePullSecrets:
      - name: my-ecr-creds

---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: flaskdemo
spec:
  selector:
    app: flaskdemo
  type: LoadBalancer
  ports:
  - name: http
    port: 8787
    targetPort: 8888
